#FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04 
FROM dmaugis/cuda8.0-cudnn5-devel-ubuntu16.04:updated

RUN apt-get -y update
#RUN apt-get -y upgrade
RUN apt-get install libeigen3-dev git python-pip -y
WORKDIR /root

RUN pip install --upgrade pip
RUN pip install Pillow
RUN pip install cython
RUN pip install numpy
RUN pip install scipy==0.13.2
RUN pip install scikit-image==0.9.3
RUN pip install scikit-learn==0.14.1
RUN git clone https://github.com/seanbell/intrinsic.git
WORKDIR /root/intrinsic/bell2014/krahenbuhl2013
RUN make
#WORKDIR /root/intrinsic
WORKDIR /inout            
#CMD /root/intrinsic/bell2014/decompose.py /inout/$1
ENTRYPOINT ["/root/intrinsic/bell2014/decompose.py"]
CMD []

